### ISSUE TITLE
Hidden parent menus clickable on Safari 12.1.1 on macOS

### ISSUE THREAD

**Issue by julian-tr** [FrDH/mmenu-light#12]
I set the offcanvas position to 'right' in the default.html demo file, but when I navigate into a child menu, the parent menu with class `mm--parent` is still clickable, although hidden off to the left. It works fine in Chrome and Firefox.

In this image I've right-clicked and chosen "Inspect Element" on a hidden parent menu item. 

![bug](https://user-images.githubusercontent.com/28651536/60899558-957cf580-a262-11e9-88b1-4d5511dfbcd1.png)

**Comment by FrDH** [comment]
arrrrrr.
ios safari has this weird bug: https://github.com/FrDH/mmenu-light/issues/11

The (really weird and hacky) fix does not take `position: "right"` into account.
I'll see if I can find a solution that does not make the CSS much more complicated. Otherwise the `position: "right"` option might become deprecated.

Thanks for reporting the issue.

**Comment by julian-tr** [comment]
Thanks. Fingers crossed you can find a solution that works for `position: "right"` as the sites I was hoping to switch to mmenu-light on have menus on the right!

**Comment by FrDH** [comment]
Should be fixed in version 2.1

**Comment by julian-tr** [comment]
Yes, all seems ok now in quick testing. Thank you.
