### ISSUE TITLE
Webpack compatibility

### ISSUE THREAD

**Issue by julmot** [FrDH/mmenu-light#7]
```
import MmenuLight from 'mmenu-light/dist/mmenu-light';
```

should export the plugin, it should not be necessary to depend on `window.MmenuLight`.

There also seems to be an inconsistency between naming dist CSS and JS files (mmenu-light.js vs mmlight.css).

**Comment by FrDH** [comment]
You can/should import from the "src" folder:
`import MmenuLight from "mmenu-light/src/mmenu-light";`

**Comment by hybridvision** [comment]
Hi @FrDH, thanks for all your work on MMenu - I've used it in the past and now I'm keen to try this new lighter version in a project. Like Julian, I'm having problems getting it to work with Webpack. I've tried importing from the src folder as you suggest but I get the following warning from Webpack:

`WARNING in ./resources/js/menu.js 3:15-25
"export 'default' (imported as 'MmenuLight') was not found in 'mmenu-light/src/mmenu-light'`

In the browser, I have this error in the console:

![image](https://user-images.githubusercontent.com/11492432/61442592-31d08780-a948-11e9-85cd-fff48c577147.png)

So I guess Webpack is really not supported currently? Do you have plans to support it?

If you need any other information about my setup, I'm happy to provide further details.

Thanks!

**Comment by FrDH** [comment]
Hmm, I guess there is missing a `export` in the `src/mmenu-light.js`.
I'll update the plugin asap.

For now you could manually add `export default MmenuLight` at the end of `src/mmenu-light.js`.

Hope this helps.

**Comment by hybridvision** [comment]
Thanks for your reply Fred! I partially got it working earlier by copying the code from `src/mmenu-light.js` into my local `menu.js` file where I have the rest of the menu setup and config.

I thought this was better than manually editing something in the `node_modules` directory where it could be overwritten at any moment. I'm also not the only one working on this project so that further constrains me... It will be great if you can update the plugin to add the export :)

Now I don't have any build or console errors but the menu only seems to partially initialise - on my menu element, I see in the developer tools that the classes `mm--main mm--offcanvas` have been added but it seems to be missing the `mm` class. If I apply that class manually, the menu flashes briefly as it slides away and then I can open it but not close it (the blocker seems to be missing). I guess there must be something going on in my build process that is interfering with it but it's hard without any errors!

I'll dig deeper and update this with anything useful I learn...

**Comment by FrDH** [comment]
Can you share your javascript?
The class "mm" should be added when the media query specified in the `enable` method matches, and removed when it doesn't.
In the below example, the menu will only be enabled (have the class "mm") when the window is less than 600 pixels wide:
````js
const node = document.querySelector( "#my-menu" );
const menu = new MmenuLight( node );

menu.enable( "(max-width: 600px)" );
menu.offcanvas();
````

**Comment by FrDH** [comment]
If you need the menu to always be enabled, you can specify "all" (or leave it empty):
````js
menu.enable( "all" );
````

**Comment by hybridvision** [comment]
Thanks Fred! In my haste I had somehow missed the fact that the `menu.enable()` call was compulsory.

Now it all works beautifully. After updating to version 2.1.1, the Webpack import also works correctly :)

For reference, here's my working code:

```js
import MmenuLight from 'mmenu-light/dist/js/mmlight';
import offcanvas from 'mmenu-light/dist/js/mmlight.offcanvas';
MmenuLight.prototype.offcanvas = offcanvas;

document.addEventListener(
    'DOMContentLoaded', () => {
        const menuSelector = '#menu';
        const menu = new MmenuLight(document.querySelector(menuSelector));

        menu.enable();
        menu.offcanvas();

        document.querySelector(`a[href="${menuSelector}"]`)
            .addEventListener('click', (event) => {
                menu.open();
                event.preventDefault();
                event.stopPropagation();
        });
    }
);
```

It looks like this ticket is resolved, at least for me. I appreciate your reactivity and help with it! Thanks!
